// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Haiku struct {
	ID         int64        `json:"id"`
	FromUserID int64        `json:"from_user_id"`
	ToUserID   int64        `json:"to_user_id"`
	Line1      string       `json:"line1"`
	Line2      string       `json:"line2"`
	Line3      string       `json:"line3"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

type User struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
}
