// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateHaiku(ctx context.Context, arg CreateHaikuParams) (sql.Result, error)
	// db/queries.sql
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error)
	GetReceivedHaikus(ctx context.Context, toUserID int64) ([]GetReceivedHaikusRow, error)
	GetSentHaikus(ctx context.Context, fromUserID int64) ([]GetSentHaikusRow, error)
	GetUser(ctx context.Context, username string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
}

var _ Querier = (*Queries)(nil)
