// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createHaiku = `-- name: CreateHaiku :execresult
INSERT INTO haikus (from_user_id, to_user_id, line1, line2, line3)
VALUES (?, ?, ?, ?, ?)
`

type CreateHaikuParams struct {
	FromUserID int64  `json:"from_user_id"`
	ToUserID   int64  `json:"to_user_id"`
	Line1      string `json:"line1"`
	Line2      string `json:"line2"`
	Line3      string `json:"line3"`
}

func (q *Queries) CreateHaiku(ctx context.Context, arg CreateHaikuParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createHaiku,
		arg.FromUserID,
		arg.ToUserID,
		arg.Line1,
		arg.Line2,
		arg.Line3,
	)
}

const createUser = `-- name: CreateUser :execresult

INSERT INTO users (username, password)
VALUES (?, ?)
`

type CreateUserParams struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

// db/queries.sql
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser, arg.Username, arg.Password)
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, username
FROM users
ORDER BY username
`

type GetAllUsersRow struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
}

func (q *Queries) GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllUsersRow{}
	for rows.Next() {
		var i GetAllUsersRow
		if err := rows.Scan(&i.ID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReceivedHaikus = `-- name: GetReceivedHaikus :many
SELECT 
    h.id,
    h.from_user_id,
    h.to_user_id,
    h.line1,
    h.line2,
    h.line3,
    h.created_at,
    u.username as from_username
FROM haikus h
JOIN users u ON h.from_user_id = u.id
WHERE h.to_user_id = ?
ORDER BY h.created_at DESC
`

type GetReceivedHaikusRow struct {
	ID           int64        `json:"id"`
	FromUserID   int64        `json:"from_user_id"`
	ToUserID     int64        `json:"to_user_id"`
	Line1        string       `json:"line1"`
	Line2        string       `json:"line2"`
	Line3        string       `json:"line3"`
	CreatedAt    sql.NullTime `json:"created_at"`
	FromUsername string       `json:"from_username"`
}

func (q *Queries) GetReceivedHaikus(ctx context.Context, toUserID int64) ([]GetReceivedHaikusRow, error) {
	rows, err := q.db.QueryContext(ctx, getReceivedHaikus, toUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetReceivedHaikusRow{}
	for rows.Next() {
		var i GetReceivedHaikusRow
		if err := rows.Scan(
			&i.ID,
			&i.FromUserID,
			&i.ToUserID,
			&i.Line1,
			&i.Line2,
			&i.Line3,
			&i.CreatedAt,
			&i.FromUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSentHaikus = `-- name: GetSentHaikus :many
SELECT 
    h.id,
    h.from_user_id,
    h.to_user_id,
    h.line1,
    h.line2,
    h.line3,
    h.created_at,
    u.username as to_username
FROM haikus h
JOIN users u ON h.to_user_id = u.id
WHERE h.from_user_id = ?
ORDER BY h.created_at DESC
`

type GetSentHaikusRow struct {
	ID         int64        `json:"id"`
	FromUserID int64        `json:"from_user_id"`
	ToUserID   int64        `json:"to_user_id"`
	Line1      string       `json:"line1"`
	Line2      string       `json:"line2"`
	Line3      string       `json:"line3"`
	CreatedAt  sql.NullTime `json:"created_at"`
	ToUsername string       `json:"to_username"`
}

func (q *Queries) GetSentHaikus(ctx context.Context, fromUserID int64) ([]GetSentHaikusRow, error) {
	rows, err := q.db.QueryContext(ctx, getSentHaikus, fromUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSentHaikusRow{}
	for rows.Next() {
		var i GetSentHaikusRow
		if err := rows.Scan(
			&i.ID,
			&i.FromUserID,
			&i.ToUserID,
			&i.Line1,
			&i.Line2,
			&i.Line3,
			&i.CreatedAt,
			&i.ToUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, username, password
FROM users
WHERE username = ?
`

func (q *Queries) GetUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, username)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.Password)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password
FROM users
WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.Password)
	return i, err
}
